### ISSUE TITLE
Download URL redirect is wrong

### ISSUE THREAD

**Issue by daym** [gobby/libinfinity#29]
http://releases.0x539.de/libinfinity/libinfinity-0.7.2.tar.gz redirects to https://github.com/gobby/libinfinity/releases/download/v0.7.2/libinfinity-0.7.2.tar.gz , which gives 404.

That's because the URL should be https://github.com/gobby/libinfinity/releases/download/0.7.2/libinfinity-0.7.2.tar.gz , note: no "v" before "0.7.2".

**Comment by pkern** [comment]
The joy of inconsistency. All other projects use a different format. Thanks for pointing that out. I added a rule specific to libinfinity to the redirector, which seems to have fixed it.
